// <auto-generated />
using System;
using CHKS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHKS.Migrations
{
    [DbContext(typeof(mydbContext))]
    [Migration("20241226071030_changeInventoryForgeinkey")]
    partial class changeInventoryForgeinkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetrole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("aspnetroles", t =>
                        {
                            t.HasTrigger("aspnetroles_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetroleclaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", t =>
                        {
                            t.HasTrigger("aspnetroleclaims_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("aspnetusers", t =>
                        {
                            t.HasTrigger("aspnetusers_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuserclaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", t =>
                        {
                            t.HasTrigger("aspnetuserclaims_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuserlogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", t =>
                        {
                            t.HasTrigger("aspnetuserlogins_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuserrole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", t =>
                        {
                            t.HasTrigger("aspnetuserroles_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetusertoken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens", t =>
                        {
                            t.HasTrigger("aspnetusertokens_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Car", b =>
                {
                    b.Property<string>("Plate")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Info")
                        .HasColumnType("longtext");

                    b.Property<short?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Plate");

                    b.ToTable("car", t =>
                        {
                            t.HasTrigger("car_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.CarBrand", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Car")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("car_brand", t =>
                        {
                            t.HasTrigger("car_brand_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<short?>("Company")
                        .HasColumnType("smallint");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CartId");

                    b.HasIndex("Plate");

                    b.ToTable("cart", t =>
                        {
                            t.HasTrigger("cart_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Connector", b =>
                {
                    b.Property<string>("GeneratedKey")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PriceOverwrite")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Qty")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("GeneratedKey");

                    b.HasIndex("CartId");

                    b.HasIndex("Product");

                    b.ToTable("connector", t =>
                        {
                            t.HasTrigger("connector_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Dailyexpense", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Expense")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("dailyexpense", t =>
                        {
                            t.HasTrigger("dailyexpense_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MigrationId");

                    b.ToTable("__efmigrationshistory", t =>
                        {
                            t.HasTrigger("__efmigrationshistory_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.History", b =>
                {
                    b.Property<string>("CashoutDate")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Baht")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Bank")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<sbyte?>("Company")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Dollar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Info")
                        .HasColumnType("longtext");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Riel")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("CashoutDate");

                    b.HasIndex("Plate");

                    b.ToTable("history", t =>
                        {
                            t.HasTrigger("history_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Historyconnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CartID");

                    b.Property<decimal?>("Export")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Product")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Qty")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("Product");

                    b.ToTable("historyconnector", t =>
                        {
                            t.HasTrigger("historyconnector_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Inventory", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Barcode")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Export")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Import")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Info")
                        .HasColumnType("longtext");

                    b.Property<short?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizeName")
                        .HasColumnType("longtext")
                        .HasColumnName("Normalize_Name");

                    b.Property<decimal>("Stock")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Code");

                    b.ToTable("inventory", t =>
                        {
                            t.HasTrigger("inventory_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Records", b =>
                {
                    b.Property<string>("DateOfChange")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Info")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("DateOfChange");

                    b.ToTable("changesrecord", t =>
                        {
                            t.HasTrigger("changesrecord_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Tags", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Tags", t =>
                        {
                            t.HasTrigger("Tags_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetroleclaim", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Aspnetrole", "Aspnetrole")
                        .WithMany("Aspnetroleclaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Aspnetrole");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuserclaim", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetuserclaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuserlogin", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetuserlogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuserrole", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Aspnetrole", "Aspnetrole")
                        .WithMany("Aspnetuserroles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CHKS.Models.mydb.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetuserroles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Aspnetrole");

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetusertoken", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetusertokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Cart", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Car", "Car")
                        .WithMany("Carts")
                        .HasForeignKey("Plate")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Connector", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Cart", "Cart")
                        .WithMany("Connectors")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CHKS.Models.mydb.Inventory", "Inventory")
                        .WithMany("Connectors")
                        .HasForeignKey("Product")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CHKS.Models.mydb.History", b =>
                {
                    b.HasOne("CHKS.Models.mydb.Car", "Car")
                        .WithMany("Histories")
                        .HasForeignKey("Plate")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Historyconnector", b =>
                {
                    b.HasOne("CHKS.Models.mydb.History", "History")
                        .WithMany("Historyconnectors")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CHKS.Models.mydb.Inventory", "Inventory")
                        .WithMany("Historyconnectors")
                        .HasForeignKey("Product")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("History");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetrole", b =>
                {
                    b.Navigation("Aspnetroleclaims");

                    b.Navigation("Aspnetuserroles");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Aspnetuser", b =>
                {
                    b.Navigation("Aspnetuserclaims");

                    b.Navigation("Aspnetuserlogins");

                    b.Navigation("Aspnetuserroles");

                    b.Navigation("Aspnetusertokens");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Car", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Cart", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("CHKS.Models.mydb.History", b =>
                {
                    b.Navigation("Historyconnectors");
                });

            modelBuilder.Entity("CHKS.Models.mydb.Inventory", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("Historyconnectors");
                });
#pragma warning restore 612, 618
        }
    }
}
