// <auto-generated />
using System;
using CHKS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHKS.Migrations
{
    [DbContext(typeof(Rardi_Context))]
    [Migration("20250726151858_RardiStructure")]
    partial class RardiStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApplicationRoleApplicationUser", b =>
                {
                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsersId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationRoleApplicationUser", t =>
                        {
                            t.HasTrigger("ApplicationRoleApplicationUser_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRole", t =>
                        {
                            t.HasTrigger("ApplicationRole_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser", t =>
                        {
                            t.HasTrigger("ApplicationUser_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetrole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", t =>
                        {
                            t.HasTrigger("AspNetRoles_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetroleclaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspnetroleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AspnetroleId");

                    b.ToTable("AspNetRoleClaims", t =>
                        {
                            t.HasTrigger("AspNetRoleClaims_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.HasTrigger("AspNetUsers_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuserclaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspnetuserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AspnetuserId");

                    b.ToTable("AspNetUserClaims", t =>
                        {
                            t.HasTrigger("AspNetUserClaims_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuserlogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AspnetuserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("AspnetuserId");

                    b.ToTable("AspNetUserLogins", t =>
                        {
                            t.HasTrigger("AspNetUserLogins_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuserrole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AspnetroleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AspnetuserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("AspnetroleId");

                    b.HasIndex("AspnetuserId");

                    b.ToTable("AspNetUserRoles", t =>
                        {
                            t.HasTrigger("AspNetUserRoles_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Aspnetusertoken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AspnetuserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("AspnetuserId");

                    b.ToTable("AspNetUserTokens", t =>
                        {
                            t.HasTrigger("AspNetUserTokens_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.CartItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PriceOverwrite")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem", t =>
                        {
                            t.HasTrigger("CartItem_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.CartModel", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CarID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cart", t =>
                        {
                            t.HasTrigger("Cart_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.CustomerModel", b =>
                {
                    b.Property<string>("PlateNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Last_visit")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone_2")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_2");

                    b.Property<int>("Vehicle_Id")
                        .HasColumnType("int");

                    b.HasKey("PlateNumber");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("Customer", t =>
                        {
                            t.HasTrigger("Customer_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees", t =>
                        {
                            t.HasTrigger("Employees_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.GroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Groups", t =>
                        {
                            t.HasTrigger("Groups_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOrderReceived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OrderReceivedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Order", t =>
                        {
                            t.HasTrigger("Order_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllowTracking")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowWarning")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Export")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Import")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Normalized_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Optimal_Stock")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventory", t =>
                        {
                            t.HasTrigger("Inventory_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.StockLogsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Time");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Seen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("ENUM('IN', 'OUT')");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Stock_Logs", t =>
                        {
                            t.HasTrigger("Stock_Logs_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.TagsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Tag")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TagsModel", t =>
                        {
                            t.HasTrigger("TagsModel_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.TransactionItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProductId");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CartID");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionsItem", t =>
                        {
                            t.HasTrigger("TransactionsItem_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.TransactionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EmployeeModelId")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeModelId");

                    b.HasIndex("Plate");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasTrigger("Transactions_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.UserNotificationStampModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("LogId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "LogId");

                    b.HasIndex("LogId");

                    b.ToTable("NotificationStampModels", t =>
                        {
                            t.HasTrigger("NotificationStampModels_Trigger");
                        });
                });

            modelBuilder.Entity("CHKS.Models.Vehicle_Model", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("Vehicle", t =>
                        {
                            t.HasTrigger("Vehicle_Trigger");
                        });
                });

            modelBuilder.Entity("EmployeeModelGroupModel", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("EmployeeModelGroupModel", t =>
                        {
                            t.HasTrigger("EmployeeModelGroupModel_Trigger");
                        });
                });

            modelBuilder.Entity("ProductModelTagsModel", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductModelTagsModel", t =>
                        {
                            t.HasTrigger("ProductModelTagsModel_Trigger");
                        });
                });

            modelBuilder.Entity("ApplicationRoleApplicationUser", b =>
                {
                    b.HasOne("CHKS.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .IsRequired();

                    b.HasOne("CHKS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .IsRequired();
                });

            modelBuilder.Entity("CHKS.Models.Aspnetroleclaim", b =>
                {
                    b.HasOne("CHKS.Models.Aspnetrole", "Aspnetrole")
                        .WithMany("Aspnetroleclaims")
                        .HasForeignKey("AspnetroleId");

                    b.Navigation("Aspnetrole");
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuserclaim", b =>
                {
                    b.HasOne("CHKS.Models.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetuserclaims")
                        .HasForeignKey("AspnetuserId");

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuserlogin", b =>
                {
                    b.HasOne("CHKS.Models.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetuserlogins")
                        .HasForeignKey("AspnetuserId");

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuserrole", b =>
                {
                    b.HasOne("CHKS.Models.Aspnetrole", "Aspnetrole")
                        .WithMany("Aspnetuserroles")
                        .HasForeignKey("AspnetroleId");

                    b.HasOne("CHKS.Models.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetuserroles")
                        .HasForeignKey("AspnetuserId");

                    b.Navigation("Aspnetrole");

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.Aspnetusertoken", b =>
                {
                    b.HasOne("CHKS.Models.Aspnetuser", "Aspnetuser")
                        .WithMany("Aspnetusertokens")
                        .HasForeignKey("AspnetuserId");

                    b.Navigation("Aspnetuser");
                });

            modelBuilder.Entity("CHKS.Models.CartItemModel", b =>
                {
                    b.HasOne("CHKS.Models.CartModel", "Cart")
                        .WithMany("CartContent")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CHKS.Models.ProductModel", "Inventory")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CHKS.Models.CartModel", b =>
                {
                    b.HasOne("CHKS.Models.CustomerModel", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CHKS.Models.CustomerModel", b =>
                {
                    b.HasOne("CHKS.Models.Vehicle_Model", "Vehicle")
                        .WithMany("Customer")
                        .HasForeignKey("Vehicle_Id")
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CHKS.Models.OrderModel", b =>
                {
                    b.HasOne("CHKS.Models.ProductModel", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CHKS.Models.ProductModel", b =>
                {
                    b.OwnsMany("CHKS.Models.ProductProfiles", "ProductProfiles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Profile")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("Product_Profiles", null, t =>
                                {
                                    t.HasTrigger("Product_Profiles_Trigger");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("ProductProfiles");
                });

            modelBuilder.Entity("CHKS.Models.StockLogsModel", b =>
                {
                    b.HasOne("CHKS.Models.EmployeeModel", "Employee")
                        .WithMany("StockLogs")
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.HasOne("CHKS.Models.ProductModel", "Product")
                        .WithMany("StockLogs")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CHKS.Models.TransactionItemModel", b =>
                {
                    b.HasOne("CHKS.Models.ProductModel", "Product")
                        .WithMany("TransactionItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CHKS.Models.TransactionModel", "Transaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CHKS.Models.TransactionModel", b =>
                {
                    b.HasOne("CHKS.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.HasOne("CHKS.Models.EmployeeModel", null)
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeModelId");

                    b.HasOne("CHKS.Models.CustomerModel", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("Plate")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.OwnsMany("CHKS.Models.PaymentModel", "Payments", b1 =>
                        {
                            b1.Property<Guid>("TransactionModelId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("PaymentType")
                                .HasColumnType("int");

                            b1.HasKey("TransactionModelId", "Id");

                            b1.ToTable("Transaction_Payments", null, t =>
                                {
                                    t.HasTrigger("Transaction_Payments_Trigger");
                                });

                            b1.WithOwner()
                                .HasForeignKey("TransactionModelId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("Payments");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHKS.Models.UserNotificationStampModel", b =>
                {
                    b.HasOne("CHKS.Models.StockLogsModel", "Log")
                        .WithMany()
                        .HasForeignKey("LogId")
                        .IsRequired();

                    b.HasOne("CHKS.Models.Aspnetuser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmployeeModelGroupModel", b =>
                {
                    b.HasOne("CHKS.Models.EmployeeModel", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.HasOne("CHKS.Models.GroupModel", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .IsRequired();
                });

            modelBuilder.Entity("ProductModelTagsModel", b =>
                {
                    b.HasOne("CHKS.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("CHKS.Models.TagsModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .IsRequired();
                });

            modelBuilder.Entity("CHKS.Models.Aspnetrole", b =>
                {
                    b.Navigation("Aspnetroleclaims");

                    b.Navigation("Aspnetuserroles");
                });

            modelBuilder.Entity("CHKS.Models.Aspnetuser", b =>
                {
                    b.Navigation("Aspnetuserclaims");

                    b.Navigation("Aspnetuserlogins");

                    b.Navigation("Aspnetuserroles");

                    b.Navigation("Aspnetusertokens");
                });

            modelBuilder.Entity("CHKS.Models.CartModel", b =>
                {
                    b.Navigation("CartContent");
                });

            modelBuilder.Entity("CHKS.Models.CustomerModel", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CHKS.Models.EmployeeModel", b =>
                {
                    b.Navigation("StockLogs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CHKS.Models.ProductModel", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("StockLogs");

                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("CHKS.Models.TransactionModel", b =>
                {
                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("CHKS.Models.Vehicle_Model", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
